/**
 * ISO 3166-1 alpha-2 → alpha-3, used to turn a world-map click
 * (world-atlas gives a country name; Vercel's geo header gives alpha-2)
 * into the ISO3 code geoBoundaries' API needs
 * (GET /api/current/gbOpen/{ISO3}/{ADM1|ADM2}/).
 *
 * Comprehensive (covers every country that has real ADM1/ADM2 shapes to
 * drill into) — this was a hand-picked ~24-country shortlist at first,
 * which meant clicking most of the world silently did nothing (looked
 * exactly like "the map isn't loading," because it wasn't a loading
 * state at all — drillIntoCountry() in AnalyticsMap.tsx just returns
 * early when a name isn't in this table). Unlike country-match.ts's
 * name-matching problem, alpha-2 -> alpha-3 is a fixed, unambiguous ISO
 * standard with no "which spelling does this dataset use" fuzziness, so
 * there's no meaningful accuracy risk in making this exhaustive the way
 * there was for country *names*. A handful of micro-territories with no
 * real subdivisions to show are still deliberately omitted — see
 * AnalyticsMap.tsx's non-drillable-country handling for what a viewer
 * sees when they click one of those.
 */
export const COUNTRY_ISO3: Record<string, string> = {
  AD: "AND",
  AE: "ARE",
  AF: "AFG",
  AG: "ATG",
  AL: "ALB",
  AM: "ARM",
  AO: "AGO",
  AR: "ARG",
  AT: "AUT",
  AU: "AUS",
  AZ: "AZE",
  BA: "BIH",
  BB: "BRB",
  BD: "BGD",
  BE: "BEL",
  BF: "BFA",
  BG: "BGR",
  BH: "BHR",
  BI: "BDI",
  BJ: "BEN",
  BN: "BRN",
  BO: "BOL",
  BR: "BRA",
  BS: "BHS",
  BT: "BTN",
  BW: "BWA",
  BY: "BLR",
  BZ: "BLZ",
  CA: "CAN",
  CD: "COD",
  CF: "CAF",
  CG: "COG",
  CH: "CHE",
  CI: "CIV",
  CL: "CHL",
  CM: "CMR",
  CN: "CHN",
  CO: "COL",
  CR: "CRI",
  CU: "CUB",
  CV: "CPV",
  CY: "CYP",
  CZ: "CZE",
  DE: "DEU",
  DJ: "DJI",
  DK: "DNK",
  DM: "DMA",
  DO: "DOM",
  DZ: "DZA",
  EC: "ECU",
  EE: "EST",
  EG: "EGY",
  ER: "ERI",
  ES: "ESP",
  ET: "ETH",
  FI: "FIN",
  FJ: "FJI",
  FM: "FSM",
  FR: "FRA",
  GA: "GAB",
  GB: "GBR",
  GD: "GRD",
  GE: "GEO",
  GH: "GHA",
  GM: "GMB",
  GN: "GIN",
  GQ: "GNQ",
  GR: "GRC",
  GT: "GTM",
  GW: "GNB",
  GY: "GUY",
  HN: "HND",
  HR: "HRV",
  HT: "HTI",
  HU: "HUN",
  ID: "IDN",
  IE: "IRL",
  IL: "ISR",
  IN: "IND",
  IQ: "IRQ",
  IR: "IRN",
  IS: "ISL",
  IT: "ITA",
  JM: "JAM",
  JO: "JOR",
  JP: "JPN",
  KE: "KEN",
  KG: "KGZ",
  KH: "KHM",
  KI: "KIR",
  KM: "COM",
  KN: "KNA",
  KP: "PRK",
  KR: "KOR",
  KW: "KWT",
  KZ: "KAZ",
  LA: "LAO",
  LB: "LBN",
  LC: "LCA",
  LI: "LIE",
  LK: "LKA",
  LR: "LBR",
  LS: "LSO",
  LT: "LTU",
  LU: "LUX",
  LV: "LVA",
  LY: "LBY",
  MA: "MAR",
  MC: "MCO",
  MD: "MDA",
  ME: "MNE",
  MG: "MDG",
  MH: "MHL",
  MK: "MKD",
  ML: "MLI",
  MM: "MMR",
  MN: "MNG",
  MR: "MRT",
  MT: "MLT",
  MU: "MUS",
  MV: "MDV",
  MW: "MWI",
  MX: "MEX",
  MY: "MYS",
  MZ: "MOZ",
  NA: "NAM",
  NE: "NER",
  NG: "NGA",
  NI: "NIC",
  NL: "NLD",
  NO: "NOR",
  NP: "NPL",
  NR: "NRU",
  NZ: "NZL",
  OM: "OMN",
  PA: "PAN",
  PE: "PER",
  PG: "PNG",
  PH: "PHL",
  PK: "PAK",
  PL: "POL",
  PS: "PSE",
  PT: "PRT",
  PW: "PLW",
  PY: "PRY",
  QA: "QAT",
  RO: "ROU",
  RS: "SRB",
  RU: "RUS",
  RW: "RWA",
  SA: "SAU",
  SB: "SLB",
  SC: "SYC",
  SD: "SDN",
  SE: "SWE",
  SG: "SGP",
  SI: "SVN",
  SK: "SVK",
  SL: "SLE",
  SM: "SMR",
  SN: "SEN",
  SO: "SOM",
  SR: "SUR",
  SS: "SSD",
  ST: "STP",
  SV: "SLV",
  SY: "SYR",
  SZ: "SWZ",
  TD: "TCD",
  TG: "TGO",
  TH: "THA",
  TJ: "TJK",
  TL: "TLS",
  TM: "TKM",
  TN: "TUN",
  TO: "TON",
  TR: "TUR",
  TT: "TTO",
  TV: "TUV",
  TW: "TWN",
  TZ: "TZA",
  UA: "UKR",
  UG: "UGA",
  US: "USA",
  UY: "URY",
  UZ: "UZB",
  VA: "VAT",
  VC: "VCT",
  VE: "VEN",
  VN: "VNM",
  VU: "VUT",
  WS: "WSM",
  YE: "YEM",
  ZA: "ZAF",
  ZM: "ZMB",
  ZW: "ZWE",
};
